// Max10_embedded_sys_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module Max10_embedded_sys_mm_interconnect_0 (
		input  wire        altpll_0_c0_clk,                                //                              altpll_0_c0.clk
		input  wire        adc_reader_0_reset_reset_bridge_in_reset_reset, // adc_reader_0_reset_reset_bridge_in_reset.reset
		input  wire [6:0]  adc_reader_0_adc_master_address,                //                  adc_reader_0_adc_master.address
		output wire        adc_reader_0_adc_master_waitrequest,            //                                         .waitrequest
		input  wire        adc_reader_0_adc_master_read,                   //                                         .read
		output wire [31:0] adc_reader_0_adc_master_readdata,               //                                         .readdata
		input  wire        adc_reader_0_adc_master_write,                  //                                         .write
		input  wire [31:0] adc_reader_0_adc_master_writedata,              //                                         .writedata
		output wire [6:0]  modular_adc_0_sample_store_csr_address,         //           modular_adc_0_sample_store_csr.address
		output wire        modular_adc_0_sample_store_csr_write,           //                                         .write
		output wire        modular_adc_0_sample_store_csr_read,            //                                         .read
		input  wire [31:0] modular_adc_0_sample_store_csr_readdata,        //                                         .readdata
		output wire [31:0] modular_adc_0_sample_store_csr_writedata        //                                         .writedata
	);

	wire         adc_reader_0_adc_master_translator_avalon_universal_master_0_waitrequest;   // modular_adc_0_sample_store_csr_translator:uav_waitrequest -> adc_reader_0_adc_master_translator:uav_waitrequest
	wire  [31:0] adc_reader_0_adc_master_translator_avalon_universal_master_0_readdata;      // modular_adc_0_sample_store_csr_translator:uav_readdata -> adc_reader_0_adc_master_translator:uav_readdata
	wire         adc_reader_0_adc_master_translator_avalon_universal_master_0_debugaccess;   // adc_reader_0_adc_master_translator:uav_debugaccess -> modular_adc_0_sample_store_csr_translator:uav_debugaccess
	wire   [8:0] adc_reader_0_adc_master_translator_avalon_universal_master_0_address;       // adc_reader_0_adc_master_translator:uav_address -> modular_adc_0_sample_store_csr_translator:uav_address
	wire         adc_reader_0_adc_master_translator_avalon_universal_master_0_read;          // adc_reader_0_adc_master_translator:uav_read -> modular_adc_0_sample_store_csr_translator:uav_read
	wire   [3:0] adc_reader_0_adc_master_translator_avalon_universal_master_0_byteenable;    // adc_reader_0_adc_master_translator:uav_byteenable -> modular_adc_0_sample_store_csr_translator:uav_byteenable
	wire         adc_reader_0_adc_master_translator_avalon_universal_master_0_readdatavalid; // modular_adc_0_sample_store_csr_translator:uav_readdatavalid -> adc_reader_0_adc_master_translator:uav_readdatavalid
	wire         adc_reader_0_adc_master_translator_avalon_universal_master_0_lock;          // adc_reader_0_adc_master_translator:uav_lock -> modular_adc_0_sample_store_csr_translator:uav_lock
	wire         adc_reader_0_adc_master_translator_avalon_universal_master_0_write;         // adc_reader_0_adc_master_translator:uav_write -> modular_adc_0_sample_store_csr_translator:uav_write
	wire  [31:0] adc_reader_0_adc_master_translator_avalon_universal_master_0_writedata;     // adc_reader_0_adc_master_translator:uav_writedata -> modular_adc_0_sample_store_csr_translator:uav_writedata
	wire   [2:0] adc_reader_0_adc_master_translator_avalon_universal_master_0_burstcount;    // adc_reader_0_adc_master_translator:uav_burstcount -> modular_adc_0_sample_store_csr_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (7),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (9),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) adc_reader_0_adc_master_translator (
		.clk                    (altpll_0_c0_clk),                                                            //                       clk.clk
		.reset                  (adc_reader_0_reset_reset_bridge_in_reset_reset),                             //                     reset.reset
		.uav_address            (adc_reader_0_adc_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (adc_reader_0_adc_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (adc_reader_0_adc_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (adc_reader_0_adc_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (adc_reader_0_adc_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (adc_reader_0_adc_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (adc_reader_0_adc_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (adc_reader_0_adc_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (adc_reader_0_adc_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (adc_reader_0_adc_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (adc_reader_0_adc_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (adc_reader_0_adc_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (adc_reader_0_adc_master_waitrequest),                                        //                          .waitrequest
		.av_read                (adc_reader_0_adc_master_read),                                               //                          .read
		.av_readdata            (adc_reader_0_adc_master_readdata),                                           //                          .readdata
		.av_write               (adc_reader_0_adc_master_write),                                              //                          .write
		.av_writedata           (adc_reader_0_adc_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                       //               (terminated)
		.av_byteenable          (4'b1111),                                                                    //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                       //               (terminated)
		.av_begintransfer       (1'b0),                                                                       //               (terminated)
		.av_chipselect          (1'b0),                                                                       //               (terminated)
		.av_readdatavalid       (),                                                                           //               (terminated)
		.av_lock                (1'b0),                                                                       //               (terminated)
		.av_debugaccess         (1'b0),                                                                       //               (terminated)
		.uav_clken              (),                                                                           //               (terminated)
		.av_clken               (1'b1),                                                                       //               (terminated)
		.uav_response           (2'b00),                                                                      //               (terminated)
		.av_response            (),                                                                           //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                       //               (terminated)
		.av_writeresponsevalid  ()                                                                            //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (7),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (9),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (2),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) modular_adc_0_sample_store_csr_translator (
		.clk                    (altpll_0_c0_clk),                                                            //                      clk.clk
		.reset                  (adc_reader_0_reset_reset_bridge_in_reset_reset),                             //                    reset.reset
		.uav_address            (adc_reader_0_adc_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (adc_reader_0_adc_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (adc_reader_0_adc_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (adc_reader_0_adc_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (adc_reader_0_adc_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (adc_reader_0_adc_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (adc_reader_0_adc_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (adc_reader_0_adc_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (adc_reader_0_adc_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (adc_reader_0_adc_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (adc_reader_0_adc_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (modular_adc_0_sample_store_csr_address),                                     //      avalon_anti_slave_0.address
		.av_write               (modular_adc_0_sample_store_csr_write),                                       //                         .write
		.av_read                (modular_adc_0_sample_store_csr_read),                                        //                         .read
		.av_readdata            (modular_adc_0_sample_store_csr_readdata),                                    //                         .readdata
		.av_writedata           (modular_adc_0_sample_store_csr_writedata),                                   //                         .writedata
		.av_begintransfer       (),                                                                           //              (terminated)
		.av_beginbursttransfer  (),                                                                           //              (terminated)
		.av_burstcount          (),                                                                           //              (terminated)
		.av_byteenable          (),                                                                           //              (terminated)
		.av_readdatavalid       (1'b0),                                                                       //              (terminated)
		.av_waitrequest         (1'b0),                                                                       //              (terminated)
		.av_writebyteenable     (),                                                                           //              (terminated)
		.av_lock                (),                                                                           //              (terminated)
		.av_chipselect          (),                                                                           //              (terminated)
		.av_clken               (),                                                                           //              (terminated)
		.uav_clken              (1'b0),                                                                       //              (terminated)
		.av_debugaccess         (),                                                                           //              (terminated)
		.av_outputenable        (),                                                                           //              (terminated)
		.uav_response           (),                                                                           //              (terminated)
		.av_response            (2'b00),                                                                      //              (terminated)
		.uav_writeresponsevalid (),                                                                           //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                        //              (terminated)
	);

endmodule
