library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity Max10_Digital_signal_processing_top is
	
	port 
	(
		MAX10_CLK1_50 : in  	 std_logic;
      SW            : in  	 std_logic_vector(9 downto 9);  -- reset_n
      LEDR          : out 	 std_logic_vector(9 downto 0);
		KEY           : in 	 std_logic_vector (1 downto 0)
	);

end entity;

architecture rtl of Max10_Digital_signal_processing_top is

	component Max10_embedded_sys is
		port (
			altpll_0_locked_conduit_export      : out std_logic;                                        -- export
			button_export                       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- export
			cap_conduit                         : in  std_logic                     := 'X';             -- conduit
			clk_clk                             : in  std_logic                     := 'X';             -- clk
			ledr_export                         : out std_logic_vector(9 downto 0);                     -- export
			modular_adc_0_adc_pll_locked_export : in  std_logic                     := 'X';             -- export
			pwm_conduit                         : out std_logic;                                        -- conduit
			reset_reset_n                       : in  std_logic                     := 'X';             -- reset_n
			adc_reader_0_control_enable         : in  std_logic                     := 'X';             -- enable
			adc_reader_0_control_busy           : out std_logic;                                        -- busy
			adc_fifo_0_status_level             : out std_logic_vector(31 downto 0);                    -- level
			adc_fifo_0_status_empty             : out std_logic;                                        -- empty
			adc_fifo_0_status_full              : out std_logic;                                        -- full
			adc_fifo_0_status_almost_full       : out std_logic;                                        -- almost_full
			adc_fifo_0_status_almost_empty      : out std_logic                                         -- almost_empty
		);
	end component Max10_embedded_sys;
	 
	-- PLL lock is generated by the Qsys PLL and consumed by the Modular ADC.
	signal pll_locked : std_logic;

    signal ledr_internal : std_logic_vector(9 downto 0);
    signal pwm_conduit_sig : std_logic;
    signal ledr_out      : std_logic_vector(9 downto 0);
	signal adc_reader_busy : std_logic;
	signal adc_fifo_level : std_logic_vector(31 downto 0);
	signal adc_fifo_empty : std_logic;
	signal adc_fifo_full : std_logic;
	signal adc_fifo_almost_full : std_logic;
	signal adc_fifo_almost_empty : std_logic;

begin

u0 : component Max10_embedded_sys
		port map (
			altpll_0_locked_conduit_export      => pll_locked,
			button_export                       => KEY,
			cap_conduit                         => KEY(0),
			clk_clk                             => MAX10_CLK1_50,
			ledr_export                         => ledr_internal,
			modular_adc_0_adc_pll_locked_export => pll_locked,
			pwm_conduit                         => pwm_conduit_sig,
			reset_reset_n                       => SW(9),                       
			adc_reader_0_control_enable         => SW(9),
			adc_reader_0_control_busy           => adc_reader_busy,
			adc_fifo_0_status_level             => adc_fifo_level,
			adc_fifo_0_status_empty             => adc_fifo_empty,
			adc_fifo_0_status_full              => adc_fifo_full,
			adc_fifo_0_status_almost_full       => adc_fifo_almost_full,
			adc_fifo_0_status_almost_empty      => adc_fifo_almost_empty
		);		


	-- Use LEDR(0) for the PWM output while leaving the rest of the LED bus under the Qsys PIO control.
	ledr_output_mux : process(ledr_internal, pwm_conduit_sig)
	begin
		ledr_out(0) <= pwm_conduit_sig;
		ledr_out(9 downto 1) <= ledr_internal(9 downto 1);
	end process;
	LEDR <= ledr_out;
end rtl;