#ifndef TIMER_HW_IP_H
#define TIMER_HW_IP_H

#include <stdint.h>
#include "system.h"
#include "io.h"

#ifndef TIMER_HW_IP_0_BASE
#define TIMER_HW_IP_0_BASE TIMER_IP_BASE
#endif

#define TIMER_VALUE_OFFSET 0x00
#define TIMER_CONTROL_OFFSET 0x04
#define TIMER_STATUS_OFFSET 0x08
#define TIMER_LOAD_OFFSET 0x0C
#define TIMER_COMPARE_OFFSET 0x10
#define TIMER_CAPTURE_OFFSET 0x14

#define TIMER_MODE_STOP 0x00
#define TIMER_MODE_RESET 0x01
#define TIMER_MODE_START 0x02
#define TIMER_MODE_LOAD 0x03
#define TIMER_MODE_MASK 0x03

#define TIMER_CAPTURE_ENABLE 0x04
#define TIMER_COUNTDOWN 0x08
#define TIMER_PWM_ENABLE 0x10

#define TIMER_PRESCALER_MASK 0xE0
#define TIMER_PRESCALER_SHIFT 5
#define TIMER_PRESCALER_1 (0u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_2 (1u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_4 (2u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_8 (3u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_16 (4u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_32 (5u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_64 (6u << TIMER_PRESCALER_SHIFT)
#define TIMER_PRESCALER_128 (7u << TIMER_PRESCALER_SHIFT)

#define TIMER_STATUS_RUNNING 0x01
#define TIMER_STATUS_OVERFLOW 0x02
#define TIMER_STATUS_COMPARE 0x04
#define TIMER_STATUS_CAPTURE_VLD 0x08
#define TIMER_STATUS_PWM_OUT 0x10

#define TIMER_READ_VALUE() IORD_32DIRECT(TIMER_HW_IP_0_BASE, TIMER_VALUE_OFFSET)
#define TIMER_READ_CONTROL() IORD_8DIRECT(TIMER_HW_IP_0_BASE, TIMER_CONTROL_OFFSET)
#define TIMER_WRITE_CONTROL(value) IOWR_8DIRECT(TIMER_HW_IP_0_BASE, TIMER_CONTROL_OFFSET, (value))
#define TIMER_READ_STATUS() IORD_8DIRECT(TIMER_HW_IP_0_BASE, TIMER_STATUS_OFFSET)
#define TIMER_WRITE_LOAD(value) IOWR_32DIRECT(TIMER_HW_IP_0_BASE, TIMER_LOAD_OFFSET, (value))
#define TIMER_WRITE_COMPARE(value) IOWR_32DIRECT(TIMER_HW_IP_0_BASE, TIMER_COMPARE_OFFSET, (value))
#define TIMER_READ_CAPTURE() IORD_32DIRECT(TIMER_HW_IP_0_BASE, TIMER_CAPTURE_OFFSET)

#endif
