# TCL File Generated by Component Editor 25.1
# Tue Apr 28 17:23:36 CEST 2026
# DO NOT MODIFY


# 
# timer_hw_ip "timer_hw_ip" v1.0
# Komlan Tovinou 2026.04.28.17:23:36
# 
# 

# 
catch {package require -exact qsys 25.1}


# 
# module timer_hw_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME timer_hw_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP own_ip
set_module_property AUTHOR "Komlan Tovinou"
set_module_property DISPLAY_NAME timer_hw_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TIMER_HW_IP
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file TIMER_HW_IP.vhd VHDL PATH HDL/TIMER_HW_IP.vhd TOP_LEVEL_FILE
add_fileset_file timer.vhd VHDL PATH HDL/timer.vhd
add_fileset_file timer_capture.vhd VHDL PATH HDL/timer_capture.vhd
add_fileset_file timer_comparator.vhd VHDL PATH HDL/timer_comparator.vhd
add_fileset_file timer_counter.vhd VHDL PATH HDL/timer_counter.vhd
add_fileset_file timer_prescaler.vhd VHDL PATH HDL/timer_prescaler.vhd
add_fileset_file timer_pwm.vhd VHDL PATH HDL/timer_pwm.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point pwm_out
# 
add_interface pwm_out conduit end
set_interface_property pwm_out associatedClock clock
set_interface_property pwm_out associatedReset reset
set_interface_property pwm_out ENABLED true
set_interface_property pwm_out EXPORT_OF ""
set_interface_property pwm_out PORT_NAME_MAP ""
set_interface_property pwm_out CMSIS_SVD_VARIABLES ""
set_interface_property pwm_out SVD_ADDRESS_GROUP ""

add_interface_port pwm_out pwm_out conduit Output 1


# 
# connection point compare
# 
add_interface compare interrupt end
set_interface_property compare associatedAddressablePoint ""
set_interface_property compare associatedClock clock
set_interface_property compare associatedReset reset
set_interface_property compare bridgedReceiverOffset ""
set_interface_property compare bridgesToReceiver ""
set_interface_property compare ENABLED true
set_interface_property compare EXPORT_OF ""
set_interface_property compare PORT_NAME_MAP ""
set_interface_property compare CMSIS_SVD_VARIABLES ""
set_interface_property compare SVD_ADDRESS_GROUP ""

add_interface_port compare compare_int irq Output 1


# 
# connection point overflow
# 
add_interface overflow interrupt end
set_interface_property overflow associatedAddressablePoint ""
set_interface_property overflow associatedClock clock
set_interface_property overflow associatedReset reset
set_interface_property overflow bridgedReceiverOffset ""
set_interface_property overflow bridgesToReceiver ""
set_interface_property overflow ENABLED true
set_interface_property overflow EXPORT_OF ""
set_interface_property overflow PORT_NAME_MAP ""
set_interface_property overflow CMSIS_SVD_VARIABLES ""
set_interface_property overflow SVD_ADDRESS_GROUP ""

add_interface_port overflow overflow_int irq Output 1


# 
# connection point avalon_slave_0_1
# 
add_interface avalon_slave_0_1 avalon end
set_interface_property avalon_slave_0_1 addressUnits WORDS
set_interface_property avalon_slave_0_1 associatedClock clock
set_interface_property avalon_slave_0_1 associatedReset reset
set_interface_property avalon_slave_0_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1 holdTime 0
set_interface_property avalon_slave_0_1 linewrapBursts false
set_interface_property avalon_slave_0_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1 readLatency 0
set_interface_property avalon_slave_0_1 readWaitTime 1
set_interface_property avalon_slave_0_1 setupTime 0
set_interface_property avalon_slave_0_1 timingUnits Cycles
set_interface_property avalon_slave_0_1 writeWaitTime 0
set_interface_property avalon_slave_0_1 ENABLED true
set_interface_property avalon_slave_0_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1 cs_n chipselect_n Input 1
add_interface_port avalon_slave_0_1 addr address Input 4
add_interface_port avalon_slave_0_1 write_n write_n Input 1
add_interface_port avalon_slave_0_1 read_n read_n Input 1
add_interface_port avalon_slave_0_1 din writedata Input 32
add_interface_port avalon_slave_0_1 dout readdata Output 32
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point capture
# 
add_interface capture conduit end
set_interface_property capture associatedClock clock
set_interface_property capture associatedReset reset
set_interface_property capture ENABLED true
set_interface_property capture EXPORT_OF ""
set_interface_property capture PORT_NAME_MAP ""
set_interface_property capture CMSIS_SVD_VARIABLES ""
set_interface_property capture SVD_ADDRESS_GROUP ""

add_interface_port capture ext_capture conduit Input 1
