name: FPGA Verification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  verification:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install GHDL
      uses: ghdl/setup-ghdl@v1
      with:
        version: nightly
        backend: mcode

    - name: Install Cocotb
      run: |
        pip install cocotb cocotb-test pytest

    - name: Run Verification
      run: |
        python ping_pong_game/run_verification.py --simulator ghdl